#!/usr/bin/env bash
TITLE="controlPanel.sh"
VERSION="${LOGOS_SCRIPT_VERSION}"
AUTHOR="${LOGOS_SCRIPT_AUTHOR}"
# generated by "${LOGOS_SCRIPT_VERSION}" script from https://github.com/ferion11/LogosLinuxInstaller

# BEGIN ENVIRONMENT
HERE="\$(dirname "\$(readlink -f "\${0}")")"

# Save IFS
IFS_TMP=\${IFS}
IFS=$'\n'

# Set config path if the user does not supply one at CLI.
if [ -z "\${CONFIG_PATH}" ]; then
    CONFIG_PATH="\${HOME}/.config/Logos_on_Linux/Logos_on_Linux.conf"; export CONFIG_PATH;
fi

# Source the config path, else use the values saved from when the script was run
# in case the config file's generation failed. This should maintain functionality
# from before the addition of the config file and after.

if [ -f \${CONFIG_PATH} ]; then
	set -a;
    source \${CONFIG_PATH};
	set +a;
	if [ -z \${WINEPREFIX} ] || [ -z \${WINE_EXE} ] || [ -z "\${WINESERVER_EXE}" ] || [ -z "\${APPDIR_BINDIR}" ] || [ -z "\${APPIMAGE_LINK_SELECTION_NAME}" ] || [ -z "\${WINETRICKSBIN}" ]; then
		echo "controlPanel.sh needs these variables set in the config file:"
		echo "- WINEPREFIX"
		echo "- WINE_EXE"
		echo "- WINESERVER_EXE"
		echo "- APPDIR_BINDIR"
		echo "- APPIMAGE_LINK_SELECTION_NAME"
		echo "- WINETRICKSBIN"
		echo "Config file incomplete. Exiting." >&2 && exit 1;
	fi
else
	[ -x "\${HERE}/data/bin/wine64" ] && export PATH="\${HERE}/data/bin:\${PATH}"
	export WINEPREFIX="\${HERE}/data/wine64_bottle"; export WINEPREFIX;
	export WINE_EXE="${WINE_EXE}"; export WINE_EXE;
	export WINESERVER_EXE="${WINESERVER_EXE}"; export WINESERVER_EXE;
	export APPDIR_BINDIR="${APPDIR_BINDIR}"; export APPDIR_BINDIR
	export APPIMAGE_LINK_SELECTION_NAME="${APPIMAGE_LINK_SELECTION_NAME}"; export APPIMAGE_LINK_SELECTION_NAME;
fi
if [ -z "${WINETRICKS_URL}" ]; then WINETRICKS_URL="https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"; export WINETRICKS_URL; fi

if [ -z "\${WINEDEBUG}" ]; then WINEDEBUG="fixme-all,err-all"; export WINEDEBUG; fi # Make wine output less verbose
# END ENVIRONMENT
# BEGIN FUNCTION DECLARATIONS
usage() {
cat << EEOF
\$TITLE, by \$AUTHOR, \$VERSION.

Usage: ./\$TITLE
Interact with ${FLPRODUCT} Bible Software in Wine on Linux.

Options:
    -h   --help               Prints this help message and exit.
    -v   --version            Prints version information and exit.
    -D   --debug              Makes Wine print out additional info.
    -f   --force-root         Sets LOGOS_FORCE_ROOT to true, which permits
                              the root user to run the script.
    --wine64                  Run the script's wine64 binary.
    --wineserver              Run the script's wineserver binary.
    --winetricks              Run winetricks.
	--reinstall-dependencies  Reinstall your distro's dependencies required
	                          to run Logos.
    --selectAppImage          Set the script's AppImage file.

EEOF
}
## BEGIN CHECK DEPENDENCIES FUNCTIONS
getOS() {
    if [ -f /etc/os-release ]; then
        # freedesktop.org and systemd
		# The following line is needed for SC1091:
		# shellcheck source=/dev/null
        source /etc/os-release
        OS="\${ID}"
        OS_RELEASE="\${VERSION_ID}"
    elif type lsb_release >/dev/null 2>&1; then
        # linuxbase.org
        OS="\$(lsb_release -si)"
        OS_RELEASE="\$(lsb_release -sr)"
    elif [ -f /etc/lsb-release ]; then
        # For some versions of Debian/Ubuntu without lsb_release command
		# The following line is needed for SC1091:
		# shellcheck source=/dev/null
        source /etc/lsb-release
        OS="\${DISTRIB_ID}"
		# shellcheck disable=SC2034
        OS_RELEASE="\${DISTRIB_RELEASE}"
    elif [ -f /etc/debian_version ]; then
        OS=Debian
		# shellcheck disable=SC2034
        OS_RELEASE="\$(cat /etc/debian_version)"
    elif [ -f /etc/SuSe-release ]; then
        :
    elif [ -f /etc/redhat-release ]; then
        :
    else
        OS="\$(uname -s)"
		# shellcheck disable=SC2034
        OS_RELEASE="\$(uname -r)"
    fi
}

getPackageManager() {
	if [ -x "\$(command -v sudo)" ]; then
		SUPERUSERDO="sudo"
	elif [ -x "\$(command -v doas)" ]; then
		SUPERUSERDO="doas"
	else
		:	
	fi

	if [ -x "\$(command -v apt)" ]; then
		PACKAGE_MANAGER="apt install -y"
		PACKAGES="mktemp patch lsof wget find sed grep gawk tr winbind cabextract x11-apps bc libxml2-utils curl fuse3"
	elif [ -x "\$(command -v dnf)" ]; then
		PACKAGE_MANAGER="dnf install -y"
		PACKAGES="patch mod_auth_ntlm_winbind samba-winbind cabextract bc libxml2 curl"
	elif [ -x "\$(command -v yum)" ]; then
		PACKAGE_MANAGER="yum install -y"
		PACKAGES="patch mod_auth_ntlm_winbind samba-winbind cabextract bc libxml2 curl"
	elif [ -x "\$(command -v pamac)" ]; then
		PACKAGE_MANAGER="pamac install --no-upgrade --no-confirm"
		PACKAGES="patch lsof wget sed grep gawk cabextract samba bc libxml2 curl"
	elif [ -x "\$(command -v pacman)" ]; then
		PACKAGE_MANAGER='pacman -Syu --overwrite \* --noconfirm --needed'
		PACKAGES="patch lsof wget sed grep gawk cabextract samba bc libxml2 curl print-manager system-config-printer cups-filters nss-mdns foomatic-db-engine foomatic-db-ppds foomatic-db-nonfree-ppds ghostscript glibc samba extra-rel/apparmor core-rel/libcurl-gnutls winetricks cabextract appmenu-gtk-module patch bc lib32-libjpeg-turbo qt5-virtualkeyboard wine-staging giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse libgpg-error lib32-libgpg-error alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo sqlite lib32-sqlite libxcomposite lib32-libxcomposite libxinerama lib32-libgcrypt libgcrypt lib32-libxinerama ncurses lib32-ncurses ocl-icd lib32-ocl-icd libxslt lib32-libxslt libva lib32-libva gtk3 lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader"
	elif [ -x "\$(command -v apk)" ]; then
		# PACKAGE_MANAGER="apk add"
		# PACKAGES="patch mod_auth_ntlm_winbind samba-winbind cabextract bc libxml2 curl"
		:
	elif [ -x "\$(command -v zypper)" ]; then
		# PACKAGE_MANAGER="zypper install"
		# PACKAGES=""
		:
	elif [ -x "\$(command -v pkg)" ]; then
		# PACKAGE_MANAGER="pkg install"
		# PACKAGES=""
		:
	else
		verbose && echo "Your distribution's package manager could not be determined."
	fi
	if [ -n "\${SUPERUSERDO}" ]; then export SUPERUSERDO; fi
	if [ -n "\${PACKAGE_MANAGER}" ]; then export PACKAGE_MANAGER; fi
	if [ -n "\${PACKAGES}" ]; then export PACKAGES; fi
}

installPackages() {
	"\${SUPERUSERDO}" "\${PACKAGE_MANAGER}" "$@"
}

check_commands() {
	if [ -z "\${SUPERUSERDO}" ]; then logos_error "Your distribution appears to be missing the ability to escalate privileges (e.g., sudo, doas). Please install either sudo or doas."; fi
	for cmd in "\$@"; do
		if have_dep "\${cmd}"; then
			verbose && echo "* command \${cmd} is installed!"
		else
			verbose && echo "* command \${cmd} not installed!"
			MISSING_CMD+=("\${cmd}")
		fi
	done
	if [ "\${#MISSING_CMD[@]}" -ne 0 ]; then
		if [ -n "\${PACKAGE_MANGER}" ]; then
			logos_continue_question "Your \${OS} install is missing the command(s): \${MISSING_CMD[*]}. To continue, the script will attempt to install the package(s): \${PACKAGES} by using (\${PACKAGE_MANAGER}). Proceed?" "Your system is missing the command(s) \${MISSING_CMD[*]}. Please install your distro's package(s) associated with \${MISSING_CMD[*]} for \${OS}.\n \${EXTRA_INFO}"
			if [ "\${OS}" = "Steam" ]; then
				"\${SUPERUSERDO}" steamos-readonly disable
				"\${SUPERUSERDO}" pacman-key --init
				"\${SUPERUSERDO}" pacman-key --populate archlinux
			fi
			installPackages "${PACKAGES}"
			if [ "\$OS" = "Steam" ]; then
				"\${SUPERUSERDO}" sed -i 's/mymachines resolve/mymachines mdns_minimal [NOTFOUND=return] resolve/' /etc/nsswitch.conf
				"\${SUPERUSERDO}" locale-gen
				"\${SUPERUSERDO}" systemctl enable --now avahi-daemon
				"\${SUPERUSERDO}" systemctl enable --now cups
				"\${SUPERUSERDO}" steamos-readonly enable
			fi
		else
			logos_error "The script could not determine your \${OS} install's package manager or it is unsupported. Your computer is missing the command(s) \${MISSING_CMD[*]}. Please install your distro's package(s) associated with \${MISSING_CMD[*]} for \${OS}.\n\${EXTRA_INFO}"
		fi
	fi
}
# shellcheck disable=SC2001
check_libs() {
	if [ -z "\${SUPERUSERDO}" ]; then logos_error "Your distribution appears to be missing the ability to escalate privileges (e.g., sudo, doas). Please install either sudo or doas."; fi
	for lib in "\$@"; do
		HAVE_LIB="\$(ldconfig -N -v "$(sed 's/:/ /g' <<< "\${LD_LIBRARY_PATH}")" 2>/dev/null | grep "\${lib}")"
		if [ -n "\${HAVE_LIB}" ]; then
			verbose && echo "* \${lib} is installed!"
		else
			if [ -n "\${PACKAGE_MANGER}" ]; then
				logos_continue_question "Your \${OS} install is missing the library: \${lib}. To continue, the script will attempt to install the library by using \${PACKAGE_MANAGER}. Proceed?" "Your system does not have lib: \${lib}. Please install the package associated with \${lib} for \${OS}.\n \${EXTRA_INFO}"
				installPackages "\${PACKAGES}"
			else
				logos_error "The script could not determine your \${OS} install's package manager or it is unsupported. Your computer is missing the library: \${lib}. Please install the package associated with \${lib} for \${OS}.\n \${EXTRA_INFO}"
			fi
		fi
	done
}

checkDependencies() {
	verbose && echo "Checking system for dependencies…"
	if [ "${TARGETVERSION}" = "10" ]; then
		check_commands mktemp patch lsof wget find sed grep ntlm_auth awk tr bc xmllint curl;
	elif [ "${TARGETVERSION}" = "9" ]; then
		check_commands mktemp patch lsof wget find sed grep ntlm_auth awk tr bc xmllint curl xwd cabextract;
	else logos_error "Unknown Logos version."
	fi
	verbose && echo "All dependencies found."
}

cli_download() {
	URI="\${1}"
	DESTINATION="\${2}"
	FILENAME="\${URI##*/}"

	if [ "\${DESTINATION}" != "\${DESTINATION%/}" ]; then
		TARGET="\${DESTINATION}/\${1##*/}"
		[ -d "\${DESTINATION}" ] || mkdir -p "\${DESTINATION}" || echo "Cannot create \${DESTINATION}" && exit 1
	elif [ -d "\${DESTINATION}" ]; then
		TARGET="\${DESTINATION}/${1##*/}"
	else
		TARGET="\${DESTINATION}"
		[ -d "\${DESTINATION%/*}" ] || mkdir -p "\${DESTINATION%/*}" || echo "Cannot create directory \${DESTINATION%/*}" && exit 1
	fi
	echo "\${URI}"
	wget --inet4-only -c "\${URI}" -O "\${TARGET}"
}
setWinetricks() {
	if [ -f "\${APPDIR_BINDIR}/winetricks" ]; then
		WINETRICKSBIN="\${APPDIR_BINDIR}/winetricks"
	elif [ \$(which winetricks) &> /dev/null ]; then
		LOCAL_WINETRICKS_VERSION=\$(winetricks --version | awk -F' ' '{print \$1}')
		if [ "\${LOCAL_WINETRICKS_VERSION}" -ge "20220411" ]; then
			WINETRICKSBIN="\$(which winetricks)"
		fi
	else
		if [ ! -z "\${WINETRICKS_URL}" ]; then
			cli_download "\${WINETRICKS_URL}" "\${APPDIR_BINDIR}/winetricks"
			chmod 755 "\${APPDIR_BINDIR}/winetricks"
			WINETRICKSBIN="\${APPDIR_BINDIR}/winetricks"
			if [ -z "${CONFIG_PATH}" ]; then
				sed -ri 's/(WINETRICKSBIN=)(".*")/\1TAYLOR/' "\${CONFIG_PATH}"
			fi
		else
			echo "WINETRICKS_URL not set."
		fi
	fi
	export WINETRICKSBIN
}
runWinetricks() {
	if [ ! -z "\${WINETRICKSBIN}" ] && [ -f "\${WINETRICKSBIN}" ]; then
		:
	else
		setWinetricks
	fi
    "\${WINETRICKSBIN}" "$@"
    "\${WINESERVER_EXE}" -w
}

selectAppImage() {
		echo "======= Running AppImage Selection only: ======="
		APPIMAGE_FILENAME=""
		APPIMAGE_LINK_SELECTION_NAME="\${APPIMAGE_LINK_SELECTION_NAME}"

		APPIMAGE_FULLPATH="\$(zenity --file-selection --filename="\${HERE}"/data/*.AppImage --file-filter='AppImage files | *.AppImage *.Appimage *.appImage *.appimage' --file-filter='All files | *')"
		if [ -z "\${APPIMAGE_FULLPATH}" ]; then
			echo "No *.AppImage file selected! exiting…"
			exit 1
		fi

		APPIMAGE_FILENAME="\${APPIMAGE_FULLPATH##*/}"
		APPIMAGE_DIR="\${APPIMAGE_FULLPATH%\${APPIMAGE_FILENAME}}"
		APPIMAGE_DIR="\${APPIMAGE_DIR%?}"
		#-------

		if [ "\${APPIMAGE_DIR}" != "\${HERE}/data/bin" ]; then
			if zenity --question --width=300 --height=200 --text="Warning: The AppImage isn't at \"./data/bin/ directory\"\!\nDo you want to copy the AppImage to the \"./data/bin/\" directory keeping portability?" --  title='Warning!'; then
					[ -f "\${HERE}/data/bin/\${APPIMAGE_FILENAME}" ] && rm -rf "\${HERE}/data/bin/\${APPIMAGE_FILENAME}"
					cp "\${APPIMAGE_FULLPATH}" "\${HERE}/data/bin/"
					APPIMAGE_FULLPATH="\${HERE}/data/bin/\${APPIMAGE_FILENAME}"
			else
				echo "Warning: Linking \${APPIMAGE_FULLPATH} to ./data/bin/\${APPIMAGE_LINK_SELECTION_NAME}"
					chmod +x "\${APPIMAGE_FULLPATH}"
					ln -s "\${APPIMAGE_FULLPATH}" "\${APPIMAGE_LINK_SELECTION_NAME}"
					rm -rf "\${HERE}/data/bin/\${APPIMAGE_LINK_SELECTION_NAME}"
					mv "\${APPIMAGE_LINK_SELECTION_NAME}" "\${HERE}/data/bin/"
					#(DISPLAY="" "\${HERE}/controlPanel.sh" "\${WINE_EXE}" wineboot) | zenity --progress --title="Wine Bottle update" --text="Updating Wine Bottle…" --pulsate --auto-close --no-cancel
					echo "======= AppImage Selection run done with external link! ======="
					exit 0
			fi
		fi

		echo "Info: Linking ../\${APPIMAGE_FILENAME} to ./data/bin/\${APPIMAGE_LINK_SELECTION_NAME}"
		chmod +x "\${APPIMAGE_FULLPATH}"
		ln -s "../\${HERE}/data/bin/\${APPIMAGE_FILENAME}" "\${APPIMAGE_LINK_SELECTION_NAME}"
		rm -rf "\${HERE}/data/bin/\${APPIMAGE_LINK_SELECTION_NAME}"
		mv "\${APPIMAGE_LINK_SELECTION_NAME}" "\${HERE}/data/bin/"
		#(DISPLAY="" "\${HERE}/controlPanel.sh" "\${WINE_EXE}" wineboot) | zenity --progress --title="Wine Bottle update" --text="Updating Wine Bottle…" --pulsate --auto-close --no-cancel
		echo "======= AppImage Selection run done! ======="
		exit 0
}
# END FUNCTION DECLARATIONS
# BEGIN OPTARGS
RESET_OPTARGS=true
for arg in "\$@"
do
	if [ -n "\$RESET_OPTARGS" ]; then
		unset RESET_OPTARGS
		set -- 
	fi
	case "\$arg" in # Relate long options to short options
		--help)       set -- "\$@" -h ;;
		--version)    set -- "\$@" -V ;;
		--force-root) set -- "\$@" -f ;;
		--debug)      set -- "\$@" -D ;;
		*)            set -- "\$@" "\$arg" ;;
	esac
done
OPTSTRING=':-:hvDf' # Available options

# First loop: set variable options which may affect other options
while getopts "\$OPTSTRING" opt; do
	case \$opt in
        f)  export LOGOS_FORCE_ROOT="1"; ;;
        D)  export DEBUG=true;
            WINEDEBUG=""; ;;
		\\?) echo "\$TITLE: -\$OPTARG: undefined option." >&2 && usage >&2 && exit ;;
		:)  echo "\$TITLE: -\$OPTARG: missing argument." >&2 && usage >&2 && exit ;;
	esac
done
OPTIND=1 # Reset the index.

# Second loop: determine user action
while getopts "\$OPTSTRING" opt; do
	case \$opt in
		h)  usage && exit ;;
		v)  echo "\$TITLE, \$VERSION by \$AUTHOR." && exit ;;
		-)
			case "\${OPTARG}" in
				wine64)
					shift
					"\${WINE_EXE}" "\$@"
					"\${WINESERVER_EXE}" -w
					exit 0 ;;
				wineserver)
					shift
					"\${WINESERVER_EXE}" "\$@"
					exit 0 ;;
				winetricks)
					shift
					runWinetricks;
					exit 0 ;;
				reinstall-dependencies)
					getOS;
					getPackageManager;
					checkDependencies;
					exit 0 ;;
				selectAppImage)
					selectAppImage;
     					exit 0;;
				*)
					if [ "\$OPTERR" = 1 ] && [ "\${OPTSTRING:0:1}" != ":" ]; then
						echo "\$TITLE: --\${OPTARG}: undefined option." >&2 && usage >&2 && exit
					fi
			esac;;
		\\?) echo "\$TITLE: -\$OPTARG: undefined option." >&2 && usage >&2 && exit ;;
		:)  echo "\$TITLE: -\$OPTARG: missing argument." >&2 && usage >&2 && exit ;;
	esac
done
if [ "\$OPTIND" -eq '1' ]; then
	echo "No options were passed.";
fi
shift \$((OPTIND-1))
# END OPTARGS

# BEGIN DIE IF ROOT
if [ "\$(id -u)" -eq '0' ] && [ -z "\${LOGOS_FORCE_ROOT}" ]; then
	echo "* Running Wine/winetricks as root is highly discouraged. Use -f|--force-root if you must run as root. See  https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F"
	exit 1;
fi
# END DIE IF ROOT

debug() {
	[[ \$DEBUG = true ]] && return 0 || return 1
}

debug && echo "Debug mode enabled."

"\${WINE_EXE}" control
"\${WINESERVER_EXE}" -w
#-------------------------------------------------

#------------- Ending block ----------------------
# restore IFS
IFS=\${IFS_TMP}
#-------------------------------------------------
